foreground           #e5e1e6
background           #141316

cursor               #c9bff8
cursor_text_color    #141316

selection_background #c9bff8
selection_foreground #312a58

# Black / Grey
color0 #141316
color8 #938f99

# Red
color1  #ffb4ab
color9  #ffb4ab

# Green / Primary Accent
color2  #c9bff8
color10 #c9bff8

# Yellow / Gold
color3  #d5c77a
color11 #d5c77a

# Blue / Accent
color4  #c9c3dc
color12 #c9c3dc

# Magenta (Reutiliza Tertiary para garantizar legibilidad)
color5  #d5c77a
color13 #d5c77a

# Cyan (Reutiliza Primary para que logos como el de Arch destaquen siempre)
color6  #c9bff8
color14 #c9bff8

# White / Light Grey
color7  #c9c5d0
color15 #e5e1e6
