foreground           #ece0df
background           #181212

cursor               #ffb3b0
cursor_text_color    #181212

selection_background #ffb3b0
selection_foreground #522120

# Black / Grey
color0 #181212
color8 #9f8c8b

# Red
color1  #ffb4ab
color9  #ffb4ab

# Green / Primary Accent
color2  #ffb3b0
color10 #ffb3b0

# Yellow / Gold
color3  #b3c8eb
color11 #b3c8eb

# Blue / Accent
color4  #e5bdbb
color12 #e5bdbb

# Magenta (Reutiliza Tertiary para garantizar legibilidad)
color5  #b3c8eb
color13 #b3c8eb

# Cyan (Reutiliza Primary para que logos como el de Arch destaquen siempre)
color6  #ffb3b0
color14 #ffb3b0

# White / Light Grey
color7  #d7c2c0
color15 #ece0df
