[General]
BgSource="background.png"
Font="JetBrainsMono Nerd Font"
FontSize=10
Padding=50
Radius=15
Scale=1

# --- Avatar de Usuario ---
UserBorderWidth=2
UserBorderColor="{{colors.on_surface.default.hex}}" 
UserColor="{{colors.surface.default.hex}}"

# --- Inputs de Texto (Usuario y Contraseña) ---
InputColor="{{colors.surface_container.default.hex}}"
InputTextColor="{{colors.on_surface.default.hex}}"
InputBorderColor="{{colors.primary.default.hex}}"
InputBorderWidth=3
UserPlaceholderText="Usuario"

# --- Botón de Login ---
LoginButtonTextColor="{{colors.on_primary.default.hex}}"
LoginButtonColor="{{colors.primary.default.hex}}"
LoginButtonText="Entrar"

# --- Menús Emergentes (Popups) ---
PopupColor="{{colors.surface_container_high.default.hex}}"
PopupActiveColor="{{colors.primary.default.hex}}"
PopupActiveTextColor="{{colors.on_primary.default.hex}}"

# --- Botones de las esquinas ---
SessionButtonColor="{{colors.surface_container.default.hex}}"
SessionIconColor="{{colors.on_surface.default.hex}}"
PowerButtonColor="{{colors.surface_container.default.hex}}"
PowerIconColor="{{colors.on_surface.default.hex}}"
