[General]
BgSource="background.png"
Font="JetBrainsMono Nerd Font"
GeneralFontSize=10
Padding=50
CornerRadius=15
LoginScale=1

# --- Avatar de Usuario ---
UserPictureBorderWidth=2
UserPictureBorderColor="{{colors.outline.default.hex}}"
UserPictureColor="{{colors.surface_variant.default.hex}}"

# --- Inputs de Texto (Usuario y Contraseña) ---
TextFieldColor="{{colors.surface_container.default.hex}}"
TextFieldTextColor="{{colors.on_surface.default.hex}}"
TextFieldHighlightColor="{{colors.primary.default.hex}}"
TextFieldHighlightWidth=30
UserFieldBgText="Usuario"
PasswordFieldBgText="Contraseña"

# --- Botón de Login ---
LoginButtonTextColor="{{colors.on_primary.default.hex}}"
LoginButtonBgColor="{{colors.primary.default.hex}}"
LoginButtonText="Entrar"

# --- Menús Emergentes (Popups) ---
PopupBgColor="{{colors.surface_container_high.default.hex}}"
PopupHighlightColor="{{colors.primary.default.hex}}"
PopupHighlightedTextColor="{{colors.on_primary.default.hex}}"

# --- Botones de las esquinas ---
SessionButtonColor="{{colors.surface_container.default.hex}}"
SessionIconColor="{{colors.on_surface.default.hex}}"
PowerButtonColor="{{colors.surface_container.default.hex}}"
PowerIconColor="{{colors.on_surface.default.hex}}"

# --- Fecha y Hora ---
DateColor="{{colors.on_surface.default.hex}}"
DateSize=36
DateIsBold=false
DateOpacity=1.0
DateFormat="dddd, d de MMMM"

TimeColor="{{colors.on_surface.default.hex}}"
TimeSize=48
TimeIsBold=true
TimeOpacity=1.0
TimeFormat="hh:mm AP"
